### PR TITLE
Switch to using command line arguments for settings instead of hardcoded values

### PR DESCRIPTION
**Pull request by nyalldawson**
This has a few benefits, including:

* Makes the script more git-friendly - it means manual changes don't need to be applied when updating the scripts from git
* Makes it easier to use the importer as a step in an external script

### CODE REVIEW

**Comment by minus34** [comment]
Hi Nyall, looks good!  Have you got a couple of example command lines (DOS and/or Bash) we could put in either the readme or as sample batch files?

**Comment by nyalldawson** [comment]
@minus34 how's that?

**Comment by minus34** [comment]
Thanks Nyall!

**Comment by minus34** [comment]
I've hit a limitation of either Python or my Python knowledge!

Can you please have a look at [this issue regarding inputting one or more states](https://github.com/minus34/gnaf-loader/issues/6)

**Pull request merged**
